version: '3.9'
services:
  web:
    container_name: web
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT:-80}:3000
    environment:
      # URL do backend API para o frontend
      - API_URL=${API_URL:-http://api:8080}
      # URL da API do WhatsApp para o frontend
      - NEXT_PUBLIC_WHATSAPP_API=${WHATSAPP_API_URL:-http://whatsapp-api:8081}
    networks:
      - app-network
    restart: always

  api:
    container_name: api
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT:-8080}:3000
    command: sh -c "npm run db:migrate && npm run start"
    environment:
      # Porta interna em que o API está escutando
      - PORT=3000
      # URL de conexão com o banco de dados PostgreSQL
      - DATABASE_URL=${DATABASE_URL:-postgres://${POSTGRES_USER:-docker}:${POSTGRES_PASSWORD:-docker}@db:5432/${POSTGRES_DB:-queue-dev}}
      # Chave secreta para JWT
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      # Tempo de expiração do JWT
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      # URL da API do WhatsApp para o backend
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-http://whatsapp-api:8081}
      # URL do deploy (para fins de monitoração ou callback)
      - DEPLOY_URL=${DEPLOY_URL:-http://localhost}
      # Token de acesso para integração com o Mercado Pago
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN:-}
    networks:
      - app-network
    restart: always

  whatsapp-api:
    container_name: whatsapp-api
    build:
      context: ./app/whatsapp-api
      dockerfile: Dockerfile
    ports:
      - ${WA_PORT:-8081}:3000
    environment:
      # Porta interna em que o API do WhatsApp está escutando
      - PORT=3000
    networks:
      - app-network
    restart: always

  db:
    image: bitnami/postgresql:13.16.0
    container_name: db
    ports:
      - 5432:5432
    environment:
      # Usuário do banco de dados PostgreSQL
      - POSTGRES_USER=${POSTGRES_USER:-docker}
      # Senha do usuário do banco de dados PostgreSQL
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker}
      # Nome do banco de dados PostgreSQL
      - POSTGRES_DB=${POSTGRES_DB:-queue-dev}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
